---
title: "Meta Analysis of Publicly Available Microarray Data"
author: "Alison Paquette"
date: "11/14/2016"
output: html_document
---
Load Related Packages
```{r}
library(metaArray)
library(biomaRt)
ensembl = useMart("ensembl",dataset="hsapiens_gene_ensembl")
```

```{r}
Covar<-read.csv("~/Documents/Project 1. Preterm Birth/November2016DataProcessing/Covar.csv")
rownames(Covar)<-as.character(Covar$SampleIdentifier)

#We have elected to exclude indivdiuals with Preeclampsia
NoPE<-subset(Covar,!PETstatus=="Y"|is.na(PETstatus))

Covar2<-subset(NoPE,!StudyIdentifier=="GSE44711") #Need to dop this one study because it only  has preterm infants
Covar2$StudyIdentifier<-droplevels(Covar2$StudyIdentifier)
table(Covar2$StudyIdentifier)

Preterm<-subset(Covar2,PretermGroup=="PT")
Term<-subset(Covar2,PretermGroup=="T")
rbind(table(Preterm$StudyIdentifier),table(Term$StudyIdentifier))

```

#load individually processed datasets
```{r}
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/GSE18809on1172016.RData")
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/GSE25906on1172016.RData")
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/GSE54618on1172016.RData")
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/GSE73374on1172016.RData")
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/GSE75010on1172016.RData")
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/GSE73685on1172016.RData")
load("/Users/alisonpaquette/Documents/Project 1. Preterm Birth/November2016DataProcessing/CompleteDatasets/BARNASEQon1172016.RData")

```


#Turn These Values into ExpressionSets####
```{r}
#GSE18809
pData<-subset(Covar2,StudyIdentifier=="GSE18809")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(GSE18809))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
GSE18809Eset <- new("ExpressionSet", exprs=as.matrix(GSE18809), phenoData = pData.2)


#GSE25906
pData<-subset(Covar2,StudyIdentifier=="GSE25906B")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(GSE25906))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
GSE25906Eset <- new("ExpressionSet", exprs=as.matrix(GSE25906), phenoData = pData.2)

#GSE54618
pData<-subset(Covar2,StudyIdentifier=="GSE54618")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(GSE54618))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
GSE54618Eset <- new("ExpressionSet", exprs=as.matrix(GSE54618), phenoData = pData.2)

#GSE73374
pData<-subset(Covar2,StudyIdentifier=="GSE73374")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(GSE73374))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
GSE73374Eset <- new("ExpressionSet", exprs=as.matrix(GSE73374), phenoData = pData.2)

#GSE75010
pData<-subset(Covar2,StudyIdentifier=="GSE75010")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(GSE75010))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
GSE75010Eset <- new("ExpressionSet", exprs=as.matrix(GSE75010), phenoData = pData.2)


#GSE73685
pData<-subset(Covar2,StudyIdentifier=="GSE73685")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(GSE73685))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
GSE73685Eset <- new("ExpressionSet", exprs=as.matrix(GSE73685), phenoData = pData.2)


#BARNASEQ
pData<-subset(Covar2,StudyIdentifier=="BARNASEQ")
pData<-pData[,c(2,5)]
rownames(pData)<-pData$SampleIdentifier

table(rownames(pData)==colnames(BARNASEQ))

pData.2 <- new("AnnotatedDataFrame")
pData(pData.2 ) <- pData
BARNASEQEset <- new("ExpressionSet", exprs=as.matrix(BARNASEQ), phenoData = pData.2)
```

#Generate Adjusted Effect Estimates and Variance
```{r}
#GSE18809
group<-(pData(GSE18809Eset)[,2])
levels(group) <- c(0,1)

d.Star <- getdF(as.matrix(GSE18809), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
GSE18809Results<-cbind(d.Adj,d.Var)
rownames(GSE18809Results)<-rownames(GSE18809)
colnames(GSE18809Results)<-c("GSE18809EffectEstimate","GSE18809Variance")



#GSE25906
group<-(pData(GSE25906Eset)[,2])
levels(group) <- c(0,1)

d.Star <- getdF(as.matrix(GSE25906), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
GSE25906Results<-cbind(d.Adj,d.Var)
rownames(GSE25906Results)<-rownames(GSE25906)
colnames(GSE25906Results)<-c("GSE25906EffectEstimate","GSE25906Variance")


#GSE54618
group<-(pData(GSE54618Eset)[,2])
levels(group) <- c(0,1)

d.Star <- getdF(as.matrix(GSE54618), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
GSE54618Results<-cbind(d.Adj,d.Var)
rownames(GSE54618Results)<-rownames(GSE54618)
colnames(GSE54618Results)<-c("GSE54618EffectEstimate","GSE54618Variance")


#GSE73374
group<-(pData(GSE73374Eset)[,2])
levels(group) <- c(0,1)

d.Star <- getdF(as.matrix(GSE73374), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
GSE73374Results<-cbind(d.Adj,d.Var)
rownames(GSE73374Results)<-rownames(GSE73374)
colnames(GSE73374Results)<-c("GSE73374EffectEstimate","GSE73374Variance")

#GSE75010
group<-(pData(GSE75010Eset)[,2])
levels(group) <- c(0,1)

d.Star <- getdF(as.matrix(GSE75010), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
GSE75010Results<-cbind(d.Adj,d.Var)
rownames(GSE75010Results)<-rownames(GSE75010)
colnames(GSE75010Results)<-c("GSE75010EffectEstimate","GSE75010Variance")




#GSE73685
group<-(pData(GSE73685Eset)[,2])
levels(group) <- c(0,1)

d.Star <- getdF(as.matrix(GSE73685), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
GSE73685Results<-cbind(d.Adj,d.Var)
rownames(GSE73685Results)<-rownames(GSE73685)
colnames(GSE73685Results)<-c("GSE73685EffectEstimate","GSE73685Variance")

#BARNASEQ
group<-(pData(BARNASEQEset)[,2])
levels(group) <- c(0,1)


d.Star <- getdF(as.matrix(BARNASEQ), group)  #
d.Adj<-(dstar(d.Star, length(group)))
d.Var<- sigmad(d.Adj, sum(group==0), sum(group==1))
BARNASEQResults<-cbind(d.Adj,d.Var)
rownames(BARNASEQResults)<-rownames(BARNASEQ)
colnames(BARNASEQResults)<-c("BARNASEQEffectEstimate","BARNASEQVariance")

#Create Final Datset which Contains log fold changes
MergedData<-merge(GSE18809Results,GSE54618Results,by='row.names',all=T)
rownames(MergedData)<-MergedData[,1]

MergedData<-merge(MergedData,GSE25906Results,by='row.names',all=T)
rownames(MergedData)<-MergedData[,1]

MergedData<-merge(MergedData,GSE73374Results,by='row.names',all=T)
rownames(MergedData)<-MergedData[,1]

MergedData<-merge(MergedData,GSE75010Results,by='row.names',all=T)
rownames(MergedData)<-MergedData[,1]

MergedData<-merge(MergedData,GSE73685Results,by='row.names',all=T)
rownames(MergedData)<-MergedData[,1]

MergedData<-merge(MergedData,BARNASEQResults,by='row.names',all=T)
rownames(MergedData)<-MergedData[,1]

MergedData<-MergedData[,-c(1:6)]


save(MergedData,file="MetaAnalysisEffectEstimateVariance.RData")
```



#Estimate FDR using Choi et al method, 2003
```{r}
#Find Overlapping Genes

GENES<-rownames(na.omit(MergedData))
length(GENES) # Adds up to what I had found before
GSE18809Eset<-GSE18809Eset[GENES,]
GSE25906Eset<-GSE25906Eset[GENES,]
GSE54618Eset<-GSE54618Eset[GENES,]
GSE73374Eset<-GSE73374Eset[GENES,]
GSE75010Eset<-GSE75010Eset[GENES,]
GSE73685Eset<-GSE73685Eset[GENES,]
BARNASEQEset<-BARNASEQEset[GENES,]
#Generate List of Expression Sets to Include
esets <- list(GSE18809Eset,GSE25906Eset,GSE75010Eset,GSE73374Eset,GSE54618Eset,GSE73685Eset,BARNASEQEset)

#Calculate Combined Effect Estimate and Z Scores
classes<-list(pData(GSE18809Eset)[,2],pData(GSE25906Eset)[,2],pData(GSE75010Eset)[,2],pData(GSE73374Eset)[,2],pData(GSE54618Eset)[,2],pData(GSE73685Eset)[,2],pData(BARNASEQEset)[,2])

theScores <- zScores(esets,classes,useREM=FALSE)

ScoresFDR <- zScoreFDR(esets, classes, useREM=FALSE, nperm=1000)

FDRAdjustedP<-ScoresFDR$"two.sided"[,"FDR"]

MetaAnalysisResults<-cbind(theScores[,c(7,8)],FDRAdjustedP)
colnames(MetaAnalysisResults)<-c("Meta.Estimate","Meta.SD","FDRAdj.P")
#Get list of HGNC_IDS from Ensembl IDs
IDs<-getBM(filters="ensembl_gene_id",attributes= c("ensembl_gene_id","hgnc_symbol"),values=rownames(MetaAnalysisResults), mart=ensembl)
rownames(IDs)<-IDs$ensembl_gene_id


MetaAnalysisResults<-merge(IDs,MetaAnalysisResults,by='row.names',all=T)
MetaAnalysisResults<-MetaAnalysisResults[,-1]
save(MetaAnalysisResults,file="MetaAnalysisResults.RData")
#Visualize didfferences of FDR Scores ALonve vs. combined dataset
FDRwholeSettwo <- sort(ScoresFDR$"two.sided"[,"FDR"])
experimentstwo <- list()
for(j in 1:7){
experimentstwo[[j]] <- sort(ScoresFDR$"two.sided"[,paste("FDR_Ex_",j,sep="")])
}


###################################################
### code chunk number 21: bb2
###################################################
theNewC <- brewer.pal(7,"Set2")


###################################################
### code chunk number 22: FDRtwo
###################################################
#####################
#                   #
#two sided z values #
#                   #
#####################

plot(FDRwholeSettwo,pch="*",col="red",ylab="FDR",xlab="Number of genes")
for(j in 1:7)
points(experimentstwo[[j]],pch=16, col=theNewC[j])
legend(8000,0.4,c("Combined set","GSE18809","GSE25906","GSE75010","GSE73374","GSE54618","GSE73685","BARNASeq"), c("red",theNewC[1:7]))


###################################################
### code chunk number 23: theFDRplots
###################################################
#par(mfrow=c(2,2))
#CountPlot(ScoresFDR,Score="FDR",kindof="neg",cols=c("red",theNewC),
#	main="Negative FDR", xlab="FDR threshold", ylab="Number of genes",CombineExp=1:2)
#CountPlot(ScoresFDR,Score="FDR",cols=c("red",theNewC),kindof="pos",
#main="Positive FDR", xlab="FDR threshold", ylab="Number of genes",Combine=1:2)
CountPlot(ScoresFDR,Score="FDR",kindof="two.sided",cols=c("red",theNewC),main="two sided FDR", xlab="FDR threshold",ylab="Number of genes",CombineExp=5)


```

